http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - {{env "TRAEFIK_USER"}}:{{env "TRAEFIK_PASSWORD_HASH"}}
          - agelos:$$2y$$05$$9heT3Ja/9cGipv2/WfXg4uj1LQyb7vUqAsiEP7L5p2PB.DlG4B8aW
  routers:
    api:
      rule: "Host(`monitor.{{env "DOMAIN"}}`)"
      entrypoints:
        - https
      # middlewares: {}
      middlewares:
        - simpleAuth
      service: api@internal
      tls:
        certResolver: "letsencrypt"

tls:
  certificates:
    - certFile: "/certs/local-cert.pem"
      keyFile: "/certs/local-key.pem"
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/local-cert.pem"
        keyFile: "/certs/local-key.pem"
  # options:
  #   default:
  #     minVersion: VersionTLS12
  #     cipherSuites:
  #       - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  #       - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  #       - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  #       - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  #       - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  #       - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  #     sniStrict: true
