entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
api:
  insecure: true
  dashboard: true
certificatesResolvers:
  letsencrypt:
    acme:
      email: "agelospanagiotakis@gmail.com"
      storage: /letsencrypt/acme.json
      tlsChallenge: {}
      httpChallenge:
        entryPoint: "http"
providers:
  docker:
    # swarmMode: true
    # exposedByDefault: false
    watch: true
    network: web
  file:
    filename: /etc/traefik/traefik_dynamic.yml
    watch: true



